name: "PR Lint"
description: "Check PR descriptions and titles for correctness"
inputs:
  repo-token:
    description: "The GitHub token to use for authentication"
    required: true
  required-sections:
    description: "The sections that are required in the PR description"
    required: false
outputs:
  errors:
    description: "Detailed error information"
runs:
  using: "node16"
  main: "dist/index.js"
