name: "PR Lint"
description: "Check PR descriptions and titles for correctness"
inputs:
  repo-token:
    description: "The GitHub token to use for authentication"
    required: true
  required-sections:
    description: "The sections that are required in the PR description"
    required: false
  allow-empty-body:
    description: "Disables checking for empty PR body"
    required: false
    default: false
  disable-title-contains-area:
    description: "Disables checking title for area slug"
    required: false
    default: false
  allow-empty-section:
    description: "Allows PR body to have empty markdown sections"
    required: false
    default: false
outputs:
  errors:
    description: "Detailed error information"
runs:
  using: "node16"
  main: "dist/index.js"
